# Generated by Django 4.2.7 on 2023-12-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanceClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slogan', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=5000)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('featureImg', models.ImageField(blank=True, upload_to='')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slogan', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=5000)),
                ('date', models.DateField()),
                ('featureImg', models.ImageField(blank=True, upload_to='')),
                ('price', models.FloatField()),
            ],
        ),
    ]
