# Generated by Django 4.2.7 on 2023-12-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceAPI', '0002_alter_event_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danceclass',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='danceclass',
            name='slogan',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
