# Generated by Django 4.2.7 on 2023-12-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceAPI', '0003_alter_danceclass_name_alter_danceclass_slogan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='featureImg',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
