# Generated by Django 4.2.7 on 2023-12-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceAPI', '0005_alter_danceclass_featureimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
