# Generated by Django 4.2.7 on 2023-12-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceAPI', '0006_alter_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slogan',
            field=models.CharField(max_length=100),
        ),
    ]
